"""UtilsLib 接口定义"""
from typing import Any, Protocol


class UtilsInterface(Protocol):

    # 多模态
    def text_to_image(self, text: str, width: int = 400, height: int = 100) -> bytes: ...
    def image_to_text(self, image_data: bytes) -> str: ...
    def text_to_audio(self, text: str) -> bytes: ...
    def audio_to_text(self, audio_data: bytes) -> str: ...
    def text_to_video(self, text: str) -> bytes: ...
    def video_to_text(self, video_data: bytes) -> str: ...

    # 编码
    def encode_text(self, text: str, encoding: str) -> str: ...
    def decode_text(self, encoded: str, encoding: str) -> str: ...

    # 文件 I/O
    def read_file(self, file_path: str, mode: str = "text") -> str | bytes: ...
    def write_file(self, file_path: str, content: str | bytes, mode: str = "text") -> bool: ...
    def validate_file_format(self, content: str, format_type: str) -> tuple[bool, str]: ...

    # 加密
    def symmetric_encrypt(self, plaintext: str, key: bytes) -> bytes: ...
    def symmetric_decrypt(self, ciphertext: bytes, key: bytes) -> str: ...

    # 序列化
    def serialize_json(self, obj: Any) -> str: ...
    def deserialize_json(self, text: str) -> Any: ...
    def serialize_yaml(self, obj: Any) -> str: ...
    def deserialize_yaml(self, text: str) -> Any: ...
